
Classes:
  name: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
              'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant',
              'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog',
              'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
              'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
              'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat',
              'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket',
              'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
              'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
              'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
              'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop',
              'mouse', 'remote', 'keyboard', 'cell_phone', 'microwave',
              'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
              'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']
  num: 80
        

Model:
  name: General # [YOLO, General]
  backbone:
    name: shufflenetv2 # [Darknet53, Resnet, shufflenetv2]
    depth: 50 # depth of ResNet model [18, 34, 50, 101, 152]
    model_size: 1.0x # model size of shufflenetv2 model[0.5x, 1.0x, 1.5x, 2.0x]
  fpn:
    name: fpn
    out_stride: [8, 16, 32] # TODO: 用于输出多少x的特征图用来检测
  head:
    name: normal
    reg_head_out: 4
    cls_head_out: 80
  
  anchors: 
    width_height: [[[3.625, 2.8125], [4.875, 6.1875], [11.65625, 10.1875]],  # Anchors for big obj
                  [[1.875, 3.8125], [3.875, 2.8125], [3.6875, 7.4375]],  # Anchors for medium obj
                  [[1.25, 1.625], [2.0, 3.75], [4.125, 2.875]]]  # Anchors for small obj
    num: 3
  
  metrics: yolo
  
  loss: fun

# train
Train:
  TRAIN_IMG_SIZE: 320
  AUGMENT: False
  MULTI_SCALE_TRAIN: False
  IOU_THRESHOLD_LOSS: 0.5
  EPOCHS: 154
  NUMBER_WORKERS: 4
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_INIT: 0.15
  LR_END: 0.000001
  WARMUP_EPOCHS: 2  # or None



# test
Test:
  TEST_IMG_SIZE: 544
  BATCH_SIZE: 1
  NUMBER_WORKERS: 0
  CONF_THRESH: 0.01
  NMS_THRESH: 0.5
  MULTI_SCALE_TEST: False
  FLIP_TEST: False
